# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_value_and_grad <- function(x) {
    .Call('RcppAutodif_get_value_and_grad', PACKAGE = 'RcppAutodif', x)
}

min_test <- function(nvar) {
    .Call('RcppAutodif_min_test', PACKAGE = 'RcppAutodif', nvar)
}

rcpp_hello_world <- function() {
    .Call('RcppAutodif_rcpp_hello_world', PACKAGE = 'RcppAutodif')
}

